<?php

/**
 * @file
 * The hook implementations for the pattern library module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function pattern_library_theme($existing, $type, $theme, $path) {
  return [
    'pattern_library_layout' => [
      'variables' => [
        'source' => NULL,
        'modifiers' => [],
        'variables' => [],
      ],
    ]
  ];
}

/**
 * Template preprocess for pattern library layout.
 *
 * @param $variables
 */
function template_preprocess_pattern_library_layout(&$variables) {
  // Set the variables so they can be access based on their name.
  if (isset($variables['variables'])) {
    foreach($variables['variables'] as $variable => $fields) {
      $variables[$variable] = $fields;
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function pattern_library_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Add entity to the build so that we can standardize on it in other portions
  // of the application.
  if (!isset($build['#entity'])) {
    $build['#entity'] = $entity;
  }
}

