pattern_library.theme_override.*:
  type: config_entity
  label: 'Pattern library theme override'
  mapping:
    id:
      type: string
      label: 'Theme override ID'
    theme_hook:
      type: string
      label: 'Theme hook'
    pattern_library:
      type: string
      label: 'Pattern library'
    pattern_mapping:
      type: sequence
      label: 'Pattern Mapping'
      sequence:
        theme_variable:
          type: string
          label: 'Theme variable'

field.formatter.settings.pattern_library_entity_properties:
  type: mapping
  label: 'Pattern library entity properties formatter settings.'
  mapping:
    property_mapping:
      type: sequence
      label: 'Property mapping'
      sequence:
        type: mapping
        label: 'Property settings'
        mapping:
          enabled_fields:
            type: sequence
            label: 'Enabled fields'
            sequence:
              type: string
              label: 'Field name'
          fields:
            type: sequence
            label: 'Field settings'
            sequence:
              type: mapping
              label: 'Field setting'
              mapping:
                property_name:
                  type: string
                  label: 'Property name'
                property_render_type:
                  type: string
                  label: 'Property render type'
                property:
                  type: string
                  label: 'Property'
